version: 1
defaults:
  base_url_host: http://127.0.0.1:4000/v1
  base_url_docker: http://llm-gateway:4000/v1
  docker_network: ai-platform
  default_model: local-general
  timeout_seconds: 120
projects:
- id: demo-app
  models:
  - local-general
  - local-embedding
  status: active
  created_at: '2026-07-20T18:29:53.908956+00:00'
  key_alias: demo-app
  litellm_key_hash: f123c04709846f5b894f304628ab182b1d0e8b3916eb0cb809c2e5c23d9bc93f
- id: taradod
  models:
  - local-general
  status: active
  created_at: '2026-07-27T18:54:40.689718+00:00'
  key_alias: taradod
  litellm_key_hash: c4aa0ef8ab8731fb5985bfcfcaf46927cea39f602bc0ada3a2d7ce87c006fc0d
- id: opencode
  models:
  - Qwen3-Coder-30B-A3B-Instruct-Q4
  - Qwen3.6-35B-A3B-UD-Q4_K_M
  - DeepSeek-R1-Distill-Qwen-32B-Q4_K_M
  - Ornith-1.0-35B-Q4_K_M
  status: active
  created_at: '2026-08-20T22:07:12.447511+00:00'
  key_alias: opencode
  litellm_key_hash: 5b9a832dd820893c0e391da4b33da153b626e78b4a09febd1cb3e9c29db8ff9c
