# n8n optional workflow client for AI Station (ADR-021).
# Sourced by scripts/ai. CPU-only; calls LiteLLM, never llama.cpp ports.

N8N_RUNTIME_DIR="${AI_STATION_DATA:-/srv/ai-station}/runtime/n8n"
N8N_HEALTH_URL="http://127.0.0.1:5678/healthz"
N8N_UI_URL="http://127.0.0.1:5678"
N8N_PROJECT_ID="n8n"
N8N_PROJECT_MODELS="Qwen3.8-27B-UD-Q4_K_M,Ornith-1.5-35B-Q4_K_M,Qwen3-Embedding-8B-Q4_K_M"

ai_n8n_usage() {
  cat <<'EOF'
Usage:
  ai n8n start [--dry-run]
  ai n8n stop
  ai n8n status
  ai n8n configure
  ai n8n uninstall [--purge] [--confirm] [--dry-run]

Optional CPU workflow client (http://127.0.0.1:5678). Not started by ai start.
Workflows and Instance AI call LiteLLM at http://llm-gateway:4000/v1 (never :8888).
Instance AI uses N8N_INSTANCE_AI_* plus N8N_LLM_API_KEY from ai n8n configure.
Sandbox uses N8N_SANDBOX_SERVICE_URL=http://sandbox-api:8080 (no host ports).
EOF
}

cmd_n8n() {
  local sub="${1:-}"
  shift || true
  case "$sub" in
    start) cmd_n8n_start "$@" ;;
    stop) cmd_n8n_stop "$@" ;;
    status) cmd_n8n_status ;;
    configure) cmd_n8n_configure ;;
    uninstall) cmd_n8n_uninstall "$@" ;;
    -h|--help|help|"") ai_n8n_usage ;;
    *)
      echo "Unknown n8n command: $sub" >&2
      ai_n8n_usage >&2
      exit 2
      ;;
  esac
}

cmd_n8n_start() {
  cmd_provider_start n8n "$@"
}

cmd_n8n_stop() {
  cmd_provider_stop n8n
}

cmd_n8n_status() {
  echo "url:     $N8N_UI_URL"
  echo "health:  $N8N_HEALTH_URL"
  echo "data:    $N8N_RUNTIME_DIR"
  if curl -fsS --max-time 3 "$N8N_HEALTH_URL" >/dev/null 2>&1; then
    echo "state:   healthy"
  else
    echo "state:   down (run: ai n8n start)"
  fi
  local env_path="$ROOT/projects/${N8N_PROJECT_ID}.env"
  if [[ -f "$env_path" ]]; then
    echo "project: $env_path"
  else
    echo "project: missing (run: ai n8n configure)"
  fi
}

ai_n8n_ensure_project() {
  local env_path="$ROOT/projects/${N8N_PROJECT_ID}.env"
  if [[ -f "$env_path" ]]; then
    echo "Project ${N8N_PROJECT_ID} already exists: ${env_path}"
  else
    cmd_projects_create "$N8N_PROJECT_ID" --models "$N8N_PROJECT_MODELS"
  fi
  python3 "$ROOT/scripts/lib/litellm_keys.py" unlimit --alias "$N8N_PROJECT_ID"
}

ai_n8n_upsert_station_env() {
  local key="$1"
  local value="$2"
  python3 - "$AI_STATION_ROOT/.env" "$key" "$value" <<'PY'
from __future__ import annotations

import pathlib
import sys

path = pathlib.Path(sys.argv[1])
key = sys.argv[2]
value = sys.argv[3]
prefix = f"{key}="
if not path.is_file():
    path.write_text(f"{prefix}{value}\n", encoding="utf-8")
    path.chmod(0o600)
    raise SystemExit(0)
lines = path.read_text(encoding="utf-8").splitlines()
out: list[str] = []
found = False
for line in lines:
    stripped = line.strip()
    if stripped.startswith(prefix) or stripped.startswith(f"#{key}="):
        if found:
            continue
        out.append(f"{prefix}{value}")
        found = True
    else:
        out.append(line)
if not found:
    if out and out[-1] != "":
        out.append("")
    out.append("# Generated by ai n8n start. Do not commit.")
    out.append(f"{prefix}{value}")
path.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
PY
}

ai_n8n_project_key() {
  local env_path="$ROOT/projects/${N8N_PROJECT_ID}.env"
  [[ -f "$env_path" ]] || return 1
  python3 - "$env_path" <<'PY'
from pathlib import Path
import sys
for line in Path(sys.argv[1]).read_text(encoding="utf-8").splitlines():
    stripped = line.strip()
    if stripped.startswith("LLM_API_KEY="):
        print(stripped.split("=", 1)[1].strip().strip('"').strip("'"), end="")
        raise SystemExit(0)
raise SystemExit(1)
PY
}

ai_n8n_sync_litellm_key() {
  local key
  key="$(ai_n8n_project_key)" || {
    echo "ERROR: missing $ROOT/projects/${N8N_PROJECT_ID}.env (run: ai n8n configure)" >&2
    return 1
  }
  ai_n8n_upsert_station_env "N8N_LLM_API_KEY" "$key"
  echo "OK: n8n Instance AI will use LiteLLM at http://llm-gateway:4000/v1"
}

ai_ensure_n8n_sandbox_secrets() {
  local key
  for key in N8N_SANDBOX_SERVICE_API_KEY N8N_SANDBOX_RUNNER_REGISTRATION_TOKEN N8N_SANDBOX_RUNNER_API_KEY; do
    if [[ -z "$(ai_load_env_value "$key")" ]]; then
      ai_n8n_upsert_station_env "$key" "$(python3 -c 'import secrets; print(secrets.token_urlsafe(36))')"
    fi
  done
  echo "OK: n8n sandbox Service URL is http://sandbox-api:8080 (key in .env)"
}

cmd_n8n_configure() {
  ai_n8n_ensure_project
  ai_n8n_sync_litellm_key
  cat <<EOF
n8n Instance AI is wired to LiteLLM (Qwen3.8-27B-UD-Q4_K_M) via compose env.
From n8n HTTP Request nodes use:
  http://llm-gateway:4000/v1/chat/completions
Canonical model:
  Qwen3.8-27B-UD-Q4_K_M
Import station templates from:
  ${ROOT}/config/clients/n8n/workflows/
UI: ${N8N_UI_URL}
Start (or recreate) n8n so the container picks up N8N_LLM_API_KEY:
  ai n8n start
EOF
}

cmd_n8n_uninstall() {
  local dry_run=0 purge=0 confirm=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) dry_run=1; shift ;;
      --purge) purge=1; shift ;;
      --confirm) confirm=1; shift ;;
      *)
        echo "Unknown argument: $1" >&2
        echo "Usage: ai n8n uninstall [--purge] [--confirm] [--dry-run]" >&2
        exit 2
        ;;
    esac
  done
  if [[ "$dry_run" -eq 1 ]]; then
    echo "DRY-RUN: would stop and remove the n8n container"
    if [[ "$purge" -eq 1 ]]; then
      echo "DRY-RUN: would delete $N8N_RUNTIME_DIR"
    fi
    return 0
  fi
  cmd_provider_stop n8n
  if [[ "$purge" -eq 1 ]]; then
    if [[ "$confirm" -ne 1 ]]; then
      echo "ERROR: --purge requires --confirm (deletes $N8N_RUNTIME_DIR)" >&2
      exit 2
    fi
    rm -rf "$N8N_RUNTIME_DIR"
    echo "OK: purged n8n runtime data"
  fi
}
